In [1]:
import sys
import pandas as pd
sys.path.append("../utils/")
from fetchdata import get_stock_price, get_news

In [2]:
startdate = "2021-05-08"
enddate = "2021-05-08"
get_news("Bitcoin", startdate, enddate, length=10, mode="ContextWeb")

Finish Request from 05/08/2021 to 05/09/2021, Get 272 articles

,title,source,date,datetime,desc,link
0,Bitcoin Tops One Day Volume of $66.55 Billion ...,americanbankingnews,"May 08, 2021",2021-05-08 04:00:00,Bitcoin (CURRENCY:BTC) traded 2.4% higher agai...,https://www.americanbankingnews.com/2021/05/08...
1,Bitcoin Tops One Day Volume of $66.55 Billion ...,americanbankingnews,"May 08, 2021",2021-05-08 12:00:00,Bitcoin (CURRENCY:BTC) traded 2.4% higher agai...,https://www.americanbankingnews.com/2021/05/08...
2,VIG Trading Up 15.2% Over Last 7 Days (VIG),americanbankingnews,"May 08, 2021",2021-05-08 04:00:00,VIG (CURRENCY:VIG) traded up 0.6% against the ...,https://www.americanbankingnews.com/2021/05/08...
3,VIG Trading Up 15.2% Over Last 7 Days (VIG),americanbankingnews,"May 08, 2021",2021-05-08 12:00:00,VIG (CURRENCY:VIG) traded up 0.6% against the ...,https://www.americanbankingnews.com/2021/05/08...
4,"Ether dazzles, Dogecoin fears, Elon Musks big ...",forextv,"May 08, 2021",2021-05-08 04:00:00,ETHs spike makes Vitalik Buterin a billionaire...,https://forextv.com/bitcoin-news/ether-dazzles...
...,...,...,...,...,...,...
267,The Facts We Can Dig Up About The Toronto-Domi...,bovnews,"May 08, 2021",2021-05-08 12:00:00,Credit Suisse raised the price target for the ...,https://bovnews.com/2021/05/08/the-facts-we-ca...
268,Ready to dive into NatWest Group plc (NWG) Sto...,bovnews,"May 08, 2021",2021-05-08 04:00:00,Historical Earnings Surprises and Revenue Fore...,https://bovnews.com/2021/05/08/ready-to-dive-i...
269,Ready to dive into NatWest Group plc (NWG) Sto...,bovnews,"May 08, 2021",2021-05-08 12:00:00,Historical Earnings Surprises and Revenue Fore...,https://bovnews.com/2021/05/08/ready-to-dive-i...
270,Magellan Midstream Partners L.P. (MMP) stock p...,bovnews,"May 08, 2021",2021-05-08 04:00:00,Wolfe Research raised the price target for the...,https://bovnews.com/2021/05/08/magellan-midstr...
271,Magellan Midstream Partners L.P. (MMP) stock p...,bovnews,"May 08, 2021",2021-05-08 12:00:00,Wolfe Research raised the price target for the...,https://bovnews.com/2021/05/08/magellan-midstr...

In [7]:
startdate = "2009-10-28"
enddate = "2009-12-31"
get_news("oil gass energy", startdate, enddate, length=10, mode="Google")

'NoneType' object is not iterable
Finish Request from 10/28/2009 to 11/06/2009, Get 222 articles
'NoneType' object is not iterable
Finish Request from 11/07/2009 to 11/16/2009, Get 160 articles
'NoneType' object is not iterable
Finish Request from 11/17/2009 to 11/26/2009, Get 226 articles
'NoneType' object is not iterable
Finish Request from 11/27/2009 to 12/06/2009, Get 196 articles
'NoneType' object is not iterable
Finish Request from 12/07/2009 to 12/16/2009, Get 272 articles
'NoneType' object is not iterable
Finish Request from 12/17/2009 to 12/26/2009, Get 138 articles
'NoneType' object is not iterable
Finish Request from 12/27/2009 to 12/31/2009, Get 84 articles

,title,source,date,datetime,desc,link
0,Leaking Timor Sea oil rig catches fire,Reuters,"Nov 1, 2009",2009-11-01 04:00:00,"SYDNEY, Nov 1 (Reuters) - An oil rig operated ...",https://www.reuters.com/article/australia-oils...
1,Leaking Timor Sea oil rig catches fire,Reuters,"Nov 1, 2009",2009-11-01 12:00:00,"SYDNEY, Nov 1 (Reuters) - An oil rig operated ...",https://www.reuters.com/article/australia-oils...
2,A Plan to Drill Roan Plateau in Colorado Meets...,The New York Times,"Oct 29, 2009",2009-10-29 04:00:00,Energy companies are looking at the Roan Plate...,https://www.nytimes.com/2009/10/30/business/en...
3,A Plan to Drill Roan Plateau in Colorado Meets...,The New York Times,"Oct 29, 2009",2009-10-29 12:00:00,Energy companies are looking at the Roan Plate...,https://www.nytimes.com/2009/10/30/business/en...
4,Colorado Springs company accused of rigging dr...,The Denver Post,"Oct 30, 2009",2009-10-30 04:00:00,"Though energy prices and drilling have fallen,...",https://www.denverpost.com/2009/10/30/colorado...
...,...,...,...,...,...,...
1293,On the Road: The Transformation of Buffalo's L...,City Room,"Dec 28, 2009",2009-12-28 12:00:00,"Omaha also has lower natural gas rates, but Bu...",https://cityroom.blogs.nytimes.com/2009/12/28/...
1294,Iran: End Slide to More Bloodshed,Payvand Iran News,"Dec 29, 2009",2009-12-29 04:00:00,... Revolution Square (Meydan-e Enghlab) in th...,http://www.payvand.com/news/09/dec/1282.html
1295,Iran: End Slide to More Bloodshed,Payvand Iran News,"Dec 29, 2009",2009-12-29 12:00:00,... Revolution Square (Meydan-e Enghlab) in th...,http://www.payvand.com/news/09/dec/1282.html
1296,Top 10 Indian companies of the decade - Rediff...,"India Business News, Stock Market, Personal Fi...","Dec 31, 2009",2009-12-31 04:00:00,"In the settlement of 2005, Mukesh retained con...",https://business.rediff.com/slide-show/2009/de...
1297,Top 10 Indian companies of the decade - Rediff...,"India Business News, Stock Market, Personal Fi...","Dec 31, 2009",2009-12-31 12:00:00,"In the settlement of 2005, Mukesh retained con...",https://business.rediff.com/slide-show/2009/de...

In [8]:
df = get_news("oil gass energy", startdate, enddate, length=10, mode="Google")
df.to_csv('energy_complement.csv', header = True)

'NoneType' object is not iterable
Finish Request from 10/28/2009 to 11/06/2009, Get 228 articles
'NoneType' object is not iterable
Finish Request from 11/07/2009 to 11/16/2009, Get 160 articles
'NoneType' object is not iterable
Finish Request from 11/17/2009 to 11/26/2009, Get 226 articles
'NoneType' object is not iterable
Finish Request from 11/27/2009 to 12/06/2009, Get 196 articles
'NoneType' object is not iterable
Finish Request from 12/07/2009 to 12/16/2009, Get 272 articles
'NoneType' object is not iterable
Finish Request from 12/17/2009 to 12/26/2009, Get 138 articles
'NoneType' object is not iterable
Finish Request from 12/27/2009 to 12/31/2009, Get 84 articles

In [5]:
import requests
import json
import re
import datetime

In [20]:
keywords="Bitcoin"
startdate="05/08/2021"
enddate="05/09/2021"
page=1

In [21]:
RAPID_API_KEY = '67f58679fcmsh1d5d86c70be0778p1320e2jsn414d9154fae0'
date_formats = ['%Y-%m-%dT%H:%M:%S', '%Y-%m-%d %H:%M:%S', '%d/%m/%Y %H:%M:%S', '%Y-%m-%dT%H:%M:%SZ']
results = []
fail_flag = 0

url1 = "https://contextualwebsearch-websearch-v1.p.rapidapi.com/api/search/NewsSearchAPI"
querystring1 = {"q":keywords,"pageNumber":"{}".format(page),"pageSize":"50","autoCorrect":"true","fromPublishedDate":startdate,
               "toPublishedDate":enddate}
headers1 = {
    'x-rapidapi-key': RAPID_API_KEY,
    'x-rapidapi-host': "contextualwebsearch-websearch-v1.p.rapidapi.com"
    }
response1 = requests.request("GET", url1, headers=headers1, params=querystring1)

In [22]:
body1 = json.loads(response1.text)
articles1 = body1["value"]

In [23]:
article = articles1[39]

In [24]:
article['datePublished']

'2021-05-08T17:54:00'

In [31]:
test = datetime.datetime.strptime(article['datePublished'], '%Y-%m-%dT%H:%M:%S').date()

In [33]:
datetime.datetime(test.year, test.month,test.day,4,0)

datetime.datetime(2021, 5, 8, 4, 0)

In [ ]:
try: 
    body1 = json.loads(response1.text)
    articles1 = body1["value"]
    n_articles = len(articles1)
    if n_articles < 50:
        fail_flag = 1

    for i, article in enumerate(articles1):
        tmp_title = article['title']
        tmp_source = article['provider']['name']
        for date_format in date_formats:
            try:
                tmp_datetime = datetime.datetime.strptime(article['datePublished'], date_format)
                tmp_date = tmp_datetime.strftime("%b %d, %Y")
                break
            except:
                continue
        tmp_desc = re.sub(r'(\r|\n|<.*?>|â€¦)+', ' ', article['description'] + ' ' + re.sub(r'(\r|\n|<.*?>|â€¦ \[\+[0-9]+ chars])+', ' ', article['body']).strip()).strip()
        tmp_link = article['url']
        results.append({'title': tmp_title, 'source': tmp_source,'date': tmp_date, 'datetime':tmp_datetime,'desc': tmp_desc, 'link': tmp_link})